version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # Uncomment to fail on warnings
  # jobs:
  #   pre_build:
  #     - sphinx-build -b html -W --keep-going docs docs/_build/html
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false
