
project: "waterbox-demo"
defaults:
  engine: openmm
  platform: auto
  temperature_K: 300
  timestep_fs: 2.0
  minimize_tolerance_kjmol: 10.0
  minimize_max_iterations: 0
  report_interval: 1000
  checkpoint_interval: 10000
  forcefield: ["charmm36.xml", "charmm36/water.xml"]
  ionic_strength_molar: 0.15
  neutralize: true
  box_padding_nm: 1.0
stages:
  - { name: minimize,   steps: 0 }
  - { name: nvt,        steps: 250000, ensemble: NVT }
  - { name: npt,        steps: 500000, ensemble: NPT }
  - { name: production, steps: 1000000, ensemble: NPT }
systems:
  - id: water3nm
    pdb: examples/waterbox/inputs/water_3nm.pdb
    forcefield: ["charmm36.xml", "charmm36/water.xml"]
sweep: { temperature_K: [300] }
